# Generated by Django 4.2.17 on 2025-07-23 13:21

import colorfield.fields
from django.db import migrations, models
import kartoza_geonode.models.preferences


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image file (.ico) to be used as favicon.The default is kartoza icon",
                        null=True,
                        upload_to="site-preferences",
                        validators=[
                            kartoza_geonode.models.preferences.validate_svg_or_image
                        ],
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image file to be used as icon on navbar.The default is kartoza.ico",
                        null=True,
                        upload_to="site-preferences",
                        validators=[
                            kartoza_geonode.models.preferences.validate_svg_or_image
                        ],
                    ),
                ),
                (
                    "main_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        help_text="Choose the main color for the site.Default is Kartoza blue",
                        image_field=None,
                        max_length=25,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "site_name",
                    models.TextField(
                        blank=True,
                        default="Kartoza GeoNode",
                        help_text="Choose the site name for navbar and on banners.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site preferences",
            },
        ),
    ]
