# Generated by Django 4.2.17 on 2025-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image file (.ico) to be used as favicon.The default is kartoza icon",
                        null=True,
                        upload_to="site-preferences",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="Upload an image file to be used as icon on navbar.The default is kartoza.ico",
                        null=True,
                        upload_to="site-preferences",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site preferences",
            },
        ),
    ]
