# Generated by Django 4.2.17 on 2025-08-07 02:16

import colorfield.fields
from django.db import migrations, models
import kartoza_geonode.models.preferences


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SitePreferences",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favicon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image file (.ico) to be used as favicon.The default is kartoza icon",
                        null=True,
                        upload_to="site-preferences",
                        validators=[
                            kartoza_geonode.models.preferences.validate_svg_or_image
                        ],
                    ),
                ),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Upload an image file to be used as icon on navbar.The default is kartoza.ico",
                        null=True,
                        upload_to="site-preferences",
                        validators=[
                            kartoza_geonode.models.preferences.validate_svg_or_image
                        ],
                    ),
                ),
                (
                    "text_color",
                    colorfield.fields.ColorField(
                        default="#3E3E3E",
                        help_text="Choose the text color for the site.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "main_color",
                    colorfield.fields.ColorField(
                        default="#57A0C7",
                        help_text="Choose the main color for the site.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "secondary_color",
                    colorfield.fields.ColorField(
                        default="#ECB44B",
                        help_text="Choose the secondary color for the site.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "sub_navbar_color",
                    colorfield.fields.ColorField(
                        default="#FFFFFF",
                        help_text="Choose the text color for the sub navbar.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "sub_navbar_background_color",
                    colorfield.fields.ColorField(
                        default="#57A0C7",
                        help_text="Choose the background color for the sub navbar.",
                        image_field=None,
                        max_length=25,
                        samples=None,
                    ),
                ),
                (
                    "site_name",
                    models.TextField(
                        default="GeoNode",
                        help_text="Choose the site name for navbar and on banners.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "site preferences",
            },
        ),
    ]
